spring:
  # ?????QQ?????
  mail:
    host: smtp.qq.com
    username:  196254331@qq.com
    password: bpdtjyehgbbfbjaj  # QQ?????????????
    port: 587
    default-encoding: UTF-8
    protocol: smtp # SMTP邮件协议
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#  datasource:
#      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://o-kr-amd2.017711.xyz:3306?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#      username: yym
#      password: "7s2JchCpQCnWGn6N"
#      driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://o-kr-amd2.017711.xyz:3306/exercise-ljm?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: ljm
    password: "PBH3D233n2kCTKNb"
    driver-class-name: com.mysql.cj.jdbc.Driver


# MyBatis-Plus??
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.email.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secretKey: "pTk5RxoqazNMf2SWBhljDVP8GsC4etnYU9xHA3b0ikL7wQ6yF1mzczXc9Bnv7Gtfd2Sqw4ErtyHjuk5Miop1Lkjh8Nmnb3Vcxz0Asdfg6"
  expiration: 12 #过期时间 小时

user:  #用户
  salt: #盐
    length: 16 #长度

knife4j:
  enable: true
